import { useState, useEffect, useRef } from 'react'
import { X, ChevronLeft, ChevronRight } from 'lucide-react'

// Responsive variants are pre-generated by scripts/optimize-gallery-images.mjs
// into public/galeria/optimized/{thumb,full}/<base>-<width>.<avif|webp|jpg>.
const THUMB_WIDTHS = [400, 800, 1200]
const FULL_WIDTHS = [960, 1600, 2400]
const THUMB_SIZES = '(min-width: 768px) 33vw, (min-width: 640px) 50vw, 100vw'
const FULL_SIZES = '95vw'

const photos = [
  { base: 'edicion',                    caption: 'Panel de edición' },
  { base: 'indices',                    caption: 'Índices de vegetación' },
  { base: 'ndvi',                       caption: 'Mapa NDVI' },
  { base: 'aoi',                        caption: 'Área de interés (AOI)' },
  { base: 'modulo_operacones_dron1',    caption: 'Módulo operaciones dron' },
  { base: 'plan_aplicacion',            caption: 'Plan de aplicación' },
  { base: 'vra_zonificacion',           caption: 'VRA · Zonificación' },
  { base: 'modulo_estres_termico',      caption: 'Módulo estrés térmico' },
  { base: 'modulo_mascara_vegetacion',  caption: 'Módulo máscara de vegetación' },
  { base: 'modulo_cobertura_vegetal',   caption: 'Módulo cobertura vegetal' },
  { base: 'swipe_mascara_pistacho',     caption: 'Swipe máscara · Pistacho' },
  { base: 'chm',                        caption: 'CHM · Modelo de altura de copa' },
  { base: 'centro_de_ayuda',            caption: 'Centro de ayuda' },
  { base: 'captura_descarga_2026',      caption: 'Página de descarga' },
  { base: 'captura_changelog_2026',     caption: 'VRA · Zonificación por índice de vegetación' },
  { base: 'captura_descarga2_2026',     caption: 'Estrés Térmico · CWSI en olivar' },
]

const videos = [
  { src: '/galeria/modulo_cobertura_vegetal.mp4',  caption: 'Módulo cobertura vegetal', poster: 'modulo_cobertura_vegetal' },
  { src: '/galeria/modulo_mascara_vegetacion.mp4', caption: 'Módulo máscara de vegetación', poster: 'modulo_mascara_vegetacion' },
]

function srcSet(base, widths, ext, folder) {
  return widths.map((w) => `/galeria/optimized/${folder}/${base}-${w}.${ext} ${w}w`).join(', ')
}

function ResponsivePicture({ base, alt, widths, folder, sizes, className, loading, fetchPriority }) {
  const largest = widths[widths.length - 1]
  return (
    <picture>
      <source type="image/avif" srcSet={srcSet(base, widths, 'avif', folder)} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet(base, widths, 'webp', folder)} sizes={sizes} />
      <img
        src={`/galeria/optimized/${folder}/${base}-${largest}.jpg`}
        srcSet={srcSet(base, widths, 'jpg', folder)}
        sizes={sizes}
        alt={alt}
        className={className}
        loading={loading}
        decoding="async"
        fetchPriority={fetchPriority}
      />
    </picture>
  )
}

function PhotoThumb({ item, onClick, eager }) {
  return (
    <button onClick={onClick} className="group relative w-full aspect-video overflow-hidden rounded-sm border border-border cursor-pointer focus:outline-none">
      <ResponsivePicture
        base={item.base}
        alt={item.caption}
        widths={THUMB_WIDTHS}
        folder="thumb"
        sizes={THUMB_SIZES}
        className="w-full h-full object-cover group-hover:scale-[1.02] transition-transform duration-200"
        loading={eager ? 'eager' : 'lazy'}
        fetchPriority={eager ? 'high' : 'auto'}
      />
      {item.caption && (
        <p className="absolute bottom-0 left-0 right-0 px-3 py-2 text-[11px] text-white bg-black/50 truncate opacity-0 group-hover:opacity-100 transition-opacity">
          {item.caption}
        </p>
      )}
    </button>
  )
}

function VideoThumb({ item, onClick }) {
  const poster = item.poster ? `/galeria/optimized/thumb/${item.poster}-400.jpg` : undefined
  return (
    <button onClick={onClick} className="group relative w-full aspect-video overflow-hidden rounded-sm border border-border bg-black cursor-pointer focus:outline-none">
      <video
        src={item.src}
        poster={poster}
        preload="none"
        muted
        className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity"
      />
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="w-10 h-10 rounded-full bg-white/20 backdrop-blur flex items-center justify-center">
          <div className="w-0 h-0 border-y-[7px] border-y-transparent border-l-[13px] border-l-white ml-1" />
        </div>
      </div>
      {item.caption && (
        <p className="absolute bottom-0 left-0 right-0 px-3 py-2 text-[11px] text-white bg-black/50 truncate">
          {item.caption}
        </p>
      )}
    </button>
  )
}

function PhotoLightbox({ items, active, onClose }) {
  const [idx, setIdx] = useState(active)
  const containerRef = useRef(null)
  const prev = () => setIdx((i) => (i - 1 + items.length) % items.length)
  const next = () => setIdx((i) => (i + 1) % items.length)
  const item = items[idx]

  useEffect(() => {
    containerRef.current?.focus()
  }, [])

  return (
    <div
      ref={containerRef}
      className="fixed inset-0 z-50 bg-black/90 flex items-center justify-center"
      onClick={onClose}
      onKeyDown={(e) => { if (e.key === 'ArrowLeft') prev(); if (e.key === 'ArrowRight') next(); if (e.key === 'Escape') onClose() }}
      tabIndex={0}
    >
      <button className="absolute left-4 text-white/60 hover:text-white p-2" onClick={(e) => { e.stopPropagation(); prev() }}>
        <ChevronLeft className="w-8 h-8" />
      </button>

      <div className="w-[95vw] max-h-[92vh] px-12" onClick={(e) => e.stopPropagation()}>
        <ResponsivePicture
          key={item.base}
          base={item.base}
          alt={item.caption}
          widths={FULL_WIDTHS}
          folder="full"
          sizes={FULL_SIZES}
          className="max-h-[88vh] max-w-full mx-auto rounded-sm object-contain"
          loading="eager"
          fetchPriority="high"
        />
        {item.caption && <p className="text-center text-white/60 text-sm mt-4">{item.caption}</p>}
      </div>

      <button className="absolute right-4 text-white/60 hover:text-white p-2" onClick={(e) => { e.stopPropagation(); next() }}>
        <ChevronRight className="w-8 h-8" />
      </button>

      <button className="absolute top-4 right-4 text-white/60 hover:text-white p-2" onClick={onClose}>
        <X className="w-6 h-6" />
      </button>

      <p className="absolute bottom-4 text-white/40 text-xs font-mono">{idx + 1} / {items.length}</p>
    </div>
  )
}

function VideoLightbox({ items, active, onClose }) {
  const [idx, setIdx] = useState(active)
  const containerRef = useRef(null)
  const prev = () => setIdx((i) => (i - 1 + items.length) % items.length)
  const next = () => setIdx((i) => (i + 1) % items.length)
  const item = items[idx]

  useEffect(() => {
    containerRef.current?.focus()
  }, [])

  return (
    <div
      ref={containerRef}
      className="fixed inset-0 z-50 bg-black/90 flex items-center justify-center"
      onClick={onClose}
      onKeyDown={(e) => { if (e.key === 'ArrowLeft') prev(); if (e.key === 'ArrowRight') next(); if (e.key === 'Escape') onClose() }}
      tabIndex={0}
    >
      <button className="absolute left-4 text-white/60 hover:text-white p-2" onClick={(e) => { e.stopPropagation(); prev() }}>
        <ChevronLeft className="w-8 h-8" />
      </button>

      <div className="w-[95vw] max-h-[92vh] px-12" onClick={(e) => e.stopPropagation()}>
        <video key={item.src} src={item.src} controls autoPlay className="max-h-[88vh] max-w-full mx-auto rounded-sm" />
        {item.caption && <p className="text-center text-white/60 text-sm mt-4">{item.caption}</p>}
      </div>

      <button className="absolute right-4 text-white/60 hover:text-white p-2" onClick={(e) => { e.stopPropagation(); next() }}>
        <ChevronRight className="w-8 h-8" />
      </button>

      <button className="absolute top-4 right-4 text-white/60 hover:text-white p-2" onClick={onClose}>
        <X className="w-6 h-6" />
      </button>

      <p className="absolute bottom-4 text-white/40 text-xs font-mono">{idx + 1} / {items.length}</p>
    </div>
  )
}

export default function Galeria() {
  const [photoIdx, setPhotoIdx] = useState(null)
  const [videoIdx, setVideoIdx] = useState(null)

  return (
    <div className="pt-16">
      <div className="bg-white border-b border-border">
        <div className="max-w-screen-xl mx-auto px-6 py-16">
          <span className="section-label">Capturas de pantalla y vídeos</span>
          <h1 className="text-4xl font-semibold tracking-tight text-text mb-3">Galería</h1>
          <p className="text-muted text-sm max-w-lg">
            Imágenes y vídeos de ZahoriFields en uso. Haz clic para ampliar.
          </p>
        </div>
      </div>

      <div className="max-w-screen-xl mx-auto px-6 py-14 space-y-16">
        {/* Fotos */}
        <section>
          <div className="flex items-center gap-4 mb-6">
            <span className="section-label">Fotos</span>
            <span className="text-xs font-mono text-muted">{photos.length} imágenes</span>
          </div>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
            {photos.map((item, i) => (
              <PhotoThumb key={item.base} item={item} eager={i < 3} onClick={() => setPhotoIdx(i)} />
            ))}
          </div>
        </section>

        {/* Videos */}
        <section>
          <div className="flex items-center gap-4 mb-6 border-t border-border pt-10">
            <span className="section-label">Vídeos</span>
            <span className="text-xs font-mono text-muted">{videos.length} vídeos</span>
          </div>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
            {videos.map((item, i) => (
              <VideoThumb key={item.src} item={item} onClick={() => setVideoIdx(i)} />
            ))}
          </div>
        </section>
      </div>

      {photoIdx !== null && (
        <PhotoLightbox items={photos} active={photoIdx} onClose={() => setPhotoIdx(null)} />
      )}
      {videoIdx !== null && (
        <VideoLightbox items={videos} active={videoIdx} onClose={() => setVideoIdx(null)} />
      )}
    </div>
  )
}
