import { useState, useEffect, useRef } from 'react'
import { X, ChevronLeft, ChevronRight } from 'lucide-react'

// Responsive variants pre-generated by scripts/optimize-gallery-images.mjs
// into public/galeria/optimized/{thumb,full}/<base>-<width>.<avif|webp|jpg>
// Only list widths that actually exist for each image (script skips upscaling)
const THUMB_WIDTHS = [400, 800, 1200]
const FULL_WIDTHS  = [960, 1600]        // 2400 omitted — many originals < 2400px

const THUMB_SIZES = '(min-width: 768px) 33vw, (min-width: 640px) 50vw, 100vw'
const FULL_SIZES  = '95vw'

const PHOTOS_PER_PAGE = 6

const photos = [
  { base: 'zahoria',                   caption: 'ZahorIA · Clasificación con IA (beta)' },
  { base: 'edicion',                   caption: 'Panel de edición' },
  { base: 'indices',                   caption: 'Índices de vegetación' },
  { base: 'ndvi',                      caption: 'Mapa NDVI' },
  { base: 'aoi',                       caption: 'Área de interés (AOI)' },
  { base: 'modulo_operacones_dron1',   caption: 'Módulo operaciones dron' },
  { base: 'plan_aplicacion',           caption: 'Plan de aplicación',
    thumbWidths: [400], fullWidths: [606] },   // original is 606 px wide
  { base: 'vra_zonificacion',          caption: 'VRA · Zonificación' },
  { base: 'modulo_estres_termico',     caption: 'Módulo estrés térmico' },
  { base: 'modulo_mascara_vegetacion', caption: 'Módulo máscara de vegetación' },
  { base: 'modulo_cobertura_vegetal',  caption: 'Módulo cobertura vegetal' },
  { base: 'swipe_mascara_pistacho',    caption: 'Swipe máscara · Pistacho' },
  { base: 'chm',                       caption: 'CHM · Modelo de altura de copa' },
  { base: 'centro_de_ayuda',          caption: 'Centro de ayuda' },
  { base: 'captura_descarga_2026',     caption: 'Página de descarga' },
  { base: 'captura_changelog_2026',    caption: 'VRA · Zonificación por índice de vegetación' },
  { base: 'captura_descarga2_2026',    caption: 'Estrés Térmico · CWSI en olivar' },
]

const videos = [
  { src: '/galeria/modulo_cobertura_vegetal.mp4',  caption: 'Módulo cobertura vegetal',      poster: 'modulo_cobertura_vegetal' },
  { src: '/galeria/modulo_mascara_vegetacion.mp4', caption: 'Módulo máscara de vegetación',  poster: 'modulo_mascara_vegetacion' },
]

// --- helpers -----------------------------------------------------------------

function srcSet(base, widths, ext, folder) {
  return widths.map((w) => `/galeria/optimized/${folder}/${base}-${w}.${ext} ${w}w`).join(', ')
}

// src fallback uses the *smallest* width — always exists even for tiny images.
// Modern browsers use srcSet; src is only a last-resort for ancient ones.
function ResponsivePicture({ base, alt, thumbWidths: tw, fullWidths: fw, folder, sizes, className, loading, fetchPriority }) {
  const widths = folder === 'thumb' ? (tw || THUMB_WIDTHS) : (fw || FULL_WIDTHS)
  const fallback = widths[0]
  return (
    <picture>
      <source type="image/avif" srcSet={srcSet(base, widths, 'avif', folder)} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet(base, widths, 'webp', folder)} sizes={sizes} />
      <img
        src={`/galeria/optimized/${folder}/${base}-${fallback}.jpg`}
        srcSet={srcSet(base, widths, 'jpg', folder)}
        sizes={sizes}
        alt={alt}
        className={className}
        loading={loading}
        decoding="async"
        fetchPriority={fetchPriority}
      />
    </picture>
  )
}

// --- thumbnails --------------------------------------------------------------

function PhotoThumb({ item, onClick, eager }) {
  return (
    <button
      onClick={onClick}
      className="group relative w-full aspect-video overflow-hidden rounded-sm border border-border cursor-pointer focus:outline-none focus-visible:ring-2 focus-visible:ring-accent"
    >
      <ResponsivePicture
        base={item.base}
        alt={item.caption}
        thumbWidths={item.thumbWidths}
        fullWidths={item.fullWidths}
        folder="thumb"
        sizes={THUMB_SIZES}
        className="w-full h-full object-cover group-hover:scale-[1.02] transition-transform duration-200"
        loading={eager ? 'eager' : 'lazy'}
        fetchPriority={eager ? 'high' : 'auto'}
      />
      {item.caption && (
        <p className="absolute bottom-0 left-0 right-0 px-3 py-2 text-[11px] text-white bg-black/50 truncate opacity-0 group-hover:opacity-100 transition-opacity">
          {item.caption}
        </p>
      )}
    </button>
  )
}

function VideoThumb({ item, onClick }) {
  const poster = item.poster ? `/galeria/optimized/thumb/${item.poster}-400.jpg` : undefined
  return (
    <button
      onClick={onClick}
      className="group relative w-full aspect-video overflow-hidden rounded-sm border border-border bg-black cursor-pointer focus:outline-none focus-visible:ring-2 focus-visible:ring-accent"
    >
      <video
        src={item.src}
        poster={poster}
        preload="none"
        muted
        className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity"
      />
      <div className="absolute inset-0 flex items-center justify-center">
        <div className="w-10 h-10 rounded-full bg-white/20 backdrop-blur flex items-center justify-center">
          <div className="w-0 h-0 border-y-[7px] border-y-transparent border-l-[13px] border-l-white ml-1" />
        </div>
      </div>
      {item.caption && (
        <p className="absolute bottom-0 left-0 right-0 px-3 py-2 text-[11px] text-white bg-black/50 truncate">
          {item.caption}
        </p>
      )}
    </button>
  )
}

// --- lightboxes --------------------------------------------------------------

function PhotoLightbox({ items, active, onClose }) {
  const [idx, setIdx] = useState(active)
  const ref = useRef(null)
  const item = items[idx]
  const prev = () => setIdx((i) => (i - 1 + items.length) % items.length)
  const next = () => setIdx((i) => (i + 1) % items.length)

  useEffect(() => { ref.current?.focus() }, [])
  useEffect(() => {
    const h = (e) => {
      if (e.key === 'ArrowLeft')  prev()
      if (e.key === 'ArrowRight') next()
      if (e.key === 'Escape')     onClose()
    }
    window.addEventListener('keydown', h)
    return () => window.removeEventListener('keydown', h)
  }, [idx])

  return (
    <div
      ref={ref}
      className="fixed inset-0 z-[200] bg-black/92 flex items-center justify-center"
      onClick={onClose}
      tabIndex={-1}
      style={{ outline: 'none' }}
    >
      <button className="absolute left-4 top-1/2 -translate-y-1/2 text-white/60 hover:text-white p-3 z-10 hover:bg-white/10 rounded-sm transition-colors" onClick={(e) => { e.stopPropagation(); prev() }}>
        <ChevronLeft className="w-7 h-7" />
      </button>

      <div className="w-[95vw] max-h-[92vh] px-14 flex flex-col items-center" onClick={(e) => e.stopPropagation()}>
        <ResponsivePicture
          key={item.base}
          base={item.base}
          alt={item.caption}
          thumbWidths={item.thumbWidths}
          fullWidths={item.fullWidths}
          folder="full"
          sizes={FULL_SIZES}
          className="max-h-[84vh] max-w-full rounded-sm object-contain"
          loading="eager"
          fetchPriority="high"
        />
        {item.caption && (
          <p className="text-center text-white/50 text-xs mt-3 tracking-wide">{item.caption}</p>
        )}
      </div>

      <button className="absolute right-4 top-1/2 -translate-y-1/2 text-white/60 hover:text-white p-3 z-10 hover:bg-white/10 rounded-sm transition-colors" onClick={(e) => { e.stopPropagation(); next() }}>
        <ChevronRight className="w-7 h-7" />
      </button>

      <button
        className="absolute top-4 right-4 z-10 flex items-center justify-center w-10 h-10 rounded-full bg-white/15 hover:bg-white/30 text-white transition-colors"
        onClick={onClose}
        title="Cerrar (Esc)"
      >
        <X className="w-5 h-5" />
      </button>

      <p className="absolute bottom-4 left-1/2 -translate-x-1/2 text-white/40 text-xs font-mono tabular-nums">
        {idx + 1} / {items.length}
      </p>
    </div>
  )
}

function VideoLightbox({ items, active, onClose }) {
  const [idx, setIdx] = useState(active)
  const ref = useRef(null)
  const item = items[idx]
  const prev = () => setIdx((i) => (i - 1 + items.length) % items.length)
  const next = () => setIdx((i) => (i + 1) % items.length)

  useEffect(() => { ref.current?.focus() }, [])
  useEffect(() => {
    const h = (e) => {
      if (e.key === 'ArrowLeft')  prev()
      if (e.key === 'ArrowRight') next()
      if (e.key === 'Escape')     onClose()
    }
    window.addEventListener('keydown', h)
    return () => window.removeEventListener('keydown', h)
  }, [idx])

  return (
    <div
      ref={ref}
      className="fixed inset-0 z-[200] bg-black/92 flex items-center justify-center"
      onClick={onClose}
      tabIndex={-1}
      style={{ outline: 'none' }}
    >
      <button className="absolute left-4 top-1/2 -translate-y-1/2 text-white/60 hover:text-white p-3 z-10 hover:bg-white/10 rounded-sm transition-colors" onClick={(e) => { e.stopPropagation(); prev() }}>
        <ChevronLeft className="w-7 h-7" />
      </button>

      <div className="w-[95vw] max-h-[92vh] px-14 flex flex-col items-center" onClick={(e) => e.stopPropagation()}>
        <video key={item.src} src={item.src} controls autoPlay className="max-h-[84vh] max-w-full rounded-sm" />
        {item.caption && (
          <p className="text-center text-white/50 text-xs mt-3 tracking-wide">{item.caption}</p>
        )}
      </div>

      <button className="absolute right-4 top-1/2 -translate-y-1/2 text-white/60 hover:text-white p-3 z-10 hover:bg-white/10 rounded-sm transition-colors" onClick={(e) => { e.stopPropagation(); next() }}>
        <ChevronRight className="w-7 h-7" />
      </button>

      <button
        className="absolute top-4 right-4 z-10 flex items-center justify-center w-10 h-10 rounded-full bg-white/15 hover:bg-white/30 text-white transition-colors"
        onClick={onClose}
        title="Cerrar (Esc)"
      >
        <X className="w-5 h-5" />
      </button>

      <p className="absolute bottom-4 left-1/2 -translate-x-1/2 text-white/40 text-xs font-mono tabular-nums">
        {idx + 1} / {items.length}
      </p>
    </div>
  )
}

// --- pagination control ------------------------------------------------------

function Pagination({ page, total, perPage, onChange }) {
  const pages = Math.ceil(total / perPage)
  if (pages <= 1) return null
  return (
    <div className="flex items-center justify-center gap-2 mt-10">
      <button
        disabled={page === 0}
        onClick={() => onChange(page - 1)}
        className="px-4 py-2 text-sm rounded-sm border border-border text-muted hover:text-text hover:border-text/30 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
      >
        ← Anterior
      </button>

      <div className="flex items-center gap-1">
        {Array.from({ length: pages }, (_, i) => (
          <button
            key={i}
            onClick={() => onChange(i)}
            className={`w-8 h-8 text-xs rounded-sm transition-colors ${
              i === page
                ? 'bg-accent text-white font-medium'
                : 'text-muted hover:text-text hover:bg-surface-2'
            }`}
          >
            {i + 1}
          </button>
        ))}
      </div>

      <button
        disabled={page >= pages - 1}
        onClick={() => onChange(page + 1)}
        className="px-4 py-2 text-sm rounded-sm border border-border text-muted hover:text-text hover:border-text/30 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
      >
        Siguiente →
      </button>
    </div>
  )
}

// --- page --------------------------------------------------------------------

export default function Galeria() {
  const [photoIdx, setPhotoIdx] = useState(null)
  const [videoIdx, setVideoIdx] = useState(null)
  const [page, setPage]         = useState(0)

  const pagePhotos  = photos.slice(page * PHOTOS_PER_PAGE, (page + 1) * PHOTOS_PER_PAGE)
  const globalStart = page * PHOTOS_PER_PAGE

  function handlePageChange(p) {
    setPage(p)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  return (
    <div className="pt-16">
      <div className="bg-white border-b border-border">
        <div className="max-w-screen-xl mx-auto px-6 py-16">
          <span className="section-label">Capturas de pantalla y vídeos</span>
          <h1 className="text-4xl font-semibold tracking-tight text-text mb-3">Galería</h1>
          <p className="text-muted text-sm max-w-lg">
            Imágenes y vídeos de ZahoriFields en uso. Haz clic para ampliar.
          </p>
        </div>
      </div>

      <div className="max-w-screen-xl mx-auto px-6 py-14 space-y-16">

        {/* Fotos */}
        <section>
          <div className="flex items-center gap-4 mb-6">
            <span className="section-label">Fotos</span>
            <span className="text-xs font-mono text-muted">{photos.length} imágenes</span>
          </div>

          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
            {pagePhotos.map((item, i) => (
              <PhotoThumb
                key={item.base}
                item={item}
                eager={i < 3 && page === 0}
                onClick={() => setPhotoIdx(globalStart + i)}
              />
            ))}
          </div>

          <Pagination
            page={page}
            total={photos.length}
            perPage={PHOTOS_PER_PAGE}
            onChange={handlePageChange}
          />
        </section>

        {/* Videos */}
        <section>
          <div className="flex items-center gap-4 mb-6 border-t border-border pt-10">
            <span className="section-label">Vídeos</span>
            <span className="text-xs font-mono text-muted">{videos.length} vídeos</span>
          </div>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
            {videos.map((item, i) => (
              <VideoThumb key={item.src} item={item} onClick={() => setVideoIdx(i)} />
            ))}
          </div>
        </section>
      </div>

      {photoIdx !== null && (
        <PhotoLightbox items={photos} active={photoIdx} onClose={() => setPhotoIdx(null)} />
      )}
      {videoIdx !== null && (
        <VideoLightbox items={videos} active={videoIdx} onClose={() => setVideoIdx(null)} />
      )}
    </div>
  )
}
